---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass 
metadata:
  name: aws-secrets # Name of the SecretProviderClass resource
  namespace: production # Namespace where the resource is located
spec:
  provider: aws  # Specifies the provider (in this case, AWS)
  secretObjects:  # Defines the secret objects to be fetched
  - secretName: api-token  # Name of the Kubernetes secret to create
    type: Opaque  # Type of the Kubernetes secret
    data:  # Data section containing the mapping of secrets from the provider
    - objectName: secret-token  # Name of the secret in the provider
      key: SECRET_TOKEN  # Key under which the secret value will be stored in the Kubernetes secret
  parameters:  # Additional parameters for the provider
    objects: |  # Configuration for fetching objects from the provider
      - objectName: prod/service/token  
        objectType: secretsmanager 
        objectAlias: secret-token  