---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::412901447215:role/api-token-access     
      #  this is my arn of iam role we have create 
